'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const { createLogger } = require('../logger');

const log = createLogger('apikeys');

/**
 * API key management.
 *
 * bot.js validates incoming uploads against a bcrypt HASH stored in
 * data/apikeys.json, so the raw key cannot be recovered from there. To let the
 * Setup Wizard / Settings page DISPLAY the key (which the user must paste into
 * SDRTrunk / TrunkRecorder anyway), we keep a local, gitignored plaintext
 * sidecar at data/apikeys.plain.json. Both files are written together.
 */

function keyFilePath() {
  return process.env.API_KEY_FILE || path.join('data', 'apikeys.json');
}
function plainFilePath() {
  const hashed = keyFilePath();
  const dir = path.dirname(hashed);
  return path.join(dir, 'apikeys.plain.json');
}

function readHashed() {
  try {
    const raw = fs.readFileSync(keyFilePath(), 'utf8');
    const arr = JSON.parse(raw);
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

function readPlain() {
  try {
    const raw = fs.readFileSync(plainFilePath(), 'utf8');
    const arr = JSON.parse(raw);
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

function writeHashed(arr) {
  const file = keyFilePath();
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(arr, null, 2));
}

function writePlain(arr) {
  const file = plainFilePath();
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(arr, null, 2), { mode: 0o600 });
}

/**
 * List keys for display. Returns metadata plus the plaintext value when we
 * have it in the sidecar; otherwise `key` is null and `recoverable` is false.
 */
function listKeys() {
  const hashed = readHashed();
  const plain = readPlain();
  const plainByName = new Map(plain.map((p) => [p.name, p.key]));
  return hashed.map((h) => ({
    name: h.name,
    disabled: !!h.disabled,
    created_at: h.created_at,
    description: h.description || '',
    key: plainByName.get(h.name) || null,
    recoverable: plainByName.has(h.name),
  }));
}

/**
 * Create (or replace) a key with the given name and return the PLAINTEXT once.
 * Stores a bcrypt hash for validation and the plaintext in the sidecar.
 */
function generateKey(name = 'Default', description = 'Created via Setup Wizard') {
  const raw = crypto.randomUUID ? crypto.randomUUID() : require('uuid').v4();
  const hash = bcrypt.hashSync(raw, 10);

  const hashed = readHashed().filter((h) => h.name !== name);
  hashed.push({ key: hash, name, disabled: false, created_at: new Date().toISOString(), description });
  writeHashed(hashed);

  const plain = readPlain().filter((p) => p.name !== name);
  plain.push({ name, key: raw, created_at: new Date().toISOString() });
  writePlain(plain);

  log.info(`Generated API key "${name}".`);
  return raw;
}

/** Ensure at least one key exists; returns the plaintext default if we have it. */
function ensureDefault() {
  const hashed = readHashed();
  if (!hashed.length) {
    return generateKey('Default', 'Auto-generated by Setup Wizard');
  }
  const plain = readPlain().find((p) => p.name === 'Default');
  return plain ? plain.key : null;
}

module.exports = { listKeys, generateKey, ensureDefault, keyFilePath, plainFilePath };
